name: udales
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  # Tests
  - numpy
  - netCDF4
  - matplotlib
  - f90nml
  # Docs
  - graphviz
  - mkdocs-material
  - mkdocs-material-extensions
  - pip:
    - mkdocs-bibtex
    - ford
